version: '2'
services:
  app:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    command: mix phoenix.server
    environment:
      - POSTGRES_USER=elixirhero
      - POSTGRES_PASSWORD=elixirhero
    depends_on:
      - postgres
  postgres:
    environment:
      - POSTGRES_USER=elixirhero
      - POSTGRES_PASSWORD=elixirhero
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
